### ISSUE TITLE
Add a way to ask an RoT archive what keys were used to sign it

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/hubtools#20]
See https://github.com/oxidecomputer/omicron/issues/3954 and https://github.com/oxidecomputer/hubris/issues/1511 for context; if we want a single TUF repo to be able to serve:

* different racks, each of which uses different keys (e.g., a `prod-rel` rack and a `staging/dev` rack), or
* a rack with a mix of acceptable keys (e.g., a rack where some sleds want `staging/dev` and others want `bart`)

then we need a way to use hubtools to inspect an archive at runtime and find out which keys signed it so we can pair it up with corresponding RoTs.

**Comment by labbott** [comment]
we now add the `SIGN` tag in the caboose
